### ISSUE TITLE
loss functions

### ISSUE THREAD

**Issue by jinhyunj** [naver-ai/pcme#3]
Hi, I found your work to be very interesting.
But I am a bit confused about your loss functions.
You computed the i2t_loss and t2i_loss separately but aren't they the same?
Am i getting something wrong?

**Comment by SanghyukChun** [comment]
@jinhyunj 
They are the same in the very specific condition
- (1) image-to-text and text-to-image loss are symmetric for the given mini-batch (i2t and t2i triplet loss is not symmetric, but MC soft contrastive loss is symmetric)
- (2) the negative sampling strategies for image and text are symmetric for the given mini-batch (previous works use "hardest negative sampling", while our method uses all possible items in the mini-batch as the negative samples -- so it is symmetric)

In my implementation, (1) and (2) are satisfied, so i2t and t2i are symmetric. You can omit one of them if you want to make the code faster.

However, in general, they are not the same. The usual cross-modal retrieval models employ triplet loss (anchor, positive and negative) with various negative sampling strategies (such as the worst-case sampling used in VSE++). In this case, i2t loss and t2i loss are not same because the modality of anchor & (positive and negative) are different. Therefore previous works use separated losses for cross-modal retrieval model training. We followed the previous practice in this work.

Unlike previous methods, we used a pair-wise loss, MC-Soft contrastive loss. We separately compute i2t and t2i losses for the extension to various negative sampling strategies (such as distance-based sampling methods). If you just follow my implementation (which collects all samples in the mini-batch as negative samples), then image-to-text and text-to-image loss are symmetric. However, if you use any other negative sampling strategy, then i2t and t2i could be different.

**Comment by jinhyunj** [comment]
Thanks.
